FROM python:3.10-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* README.md ./
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --only=main --no-root

COPY client /app/client

ENTRYPOINT ["python", "/app/client/client.py"]